### ISSUE TITLE
Push Send from Backed not working 

### ISSUE THREAD

**Issue by k0steash** [CrossGeeks/AzurePushNotificationPlugin#42]
Hallo to all,
I'm testing from Azure - portal  and it working. 
But if i send from backend - not working. 
Should i yet template register? 
I use NotificationHubClient

**Comment by k0steash** [comment]
I checked devices with GetRegistrationsByTagAsync and my device be present. 
So i send notifications: 

`Hub.SendTemplateNotificationAsync(new Dictionary<string, string> { { "message", sendvalue.ToString(Newtonsoft.Json.Formatting.None) } }, users.First());`

**Comment by k0steash** [comment]
With SendFcmNativeNotificationAsync and SendAppleNativeNotificationAsync ist working :) Tnx

**Comment by k0steash** [comment]
With SendFcmNativeNotificationAsync and SendAppleNativeNotificationAsync working

**Comment by ikeoriaku123** [comment]
> Hallo to all,
> I'm testing from Azure - portal and it working.
> But if i send from backend - not working.
> Should i yet template register?
> I use NotificationHubClient

I can give a good advice. Develop your own framework for push notification. I used the plugin which only worked for iOS but not 100%. It never worked for android. So I decided to create my own framework in order to have more control whenever ios or android is updated. I did that and it worked for me. Kudos to the people that developed this plugin but I rather implement mine
